# Generated by Django 2.1.7 on 2019-03-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='job_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='open_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='type',
            field=models.CharField(blank=True, choices=[('Strategic', 'Strategic'), ('Open', 'Open'), ('Investment', 'Investment')], default='Strategic', max_length=50),
        ),
        migrations.AlterField(
            model_name='grant',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='project_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='status',
            field=models.CharField(blank=True, choices=[('APPLIED', 'Applied'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CONTRACTED', 'Contracted'), ('COMPLETED', 'Completed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='address_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='county',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='type',
            field=models.CharField(blank=True, choices=[('SMALL_BUSINESS', 'Small Business'), ('LARGE_BUSINESS', 'Large Business'), ('SOLETRADER', 'Soletrader')], default='SMALL_BUSINESS', max_length=50),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
    ]
