# Generated by Django 2.1.7 on 2019-03-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190307_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='status',
            field=models.CharField(blank=True, choices=[('Applied', 'Applied'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Contracted', 'Contracted'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='type',
            field=models.CharField(blank=True, choices=[('Small Business', 'Small Business'), ('Large Business', 'Large Business'), ('Soletrader', 'Soletrader')], default='Small Business', max_length=50),
        ),
    ]
