# Generated by Django 2.1.7 on 2019-03-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190308_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='slug',
            field=models.SlugField(default='slug3', unique=True),
        ),
    ]
