# Generated by Django 2.1.7 on 2019-03-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('type', models.CharField(choices=[('Strategic', 'Strategic'), ('Open', 'Open'), ('Investment', 'Investment')], default='Strategic', max_length=50)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='grant',
            name='organisation',
        ),
        migrations.DeleteModel(
            name='Grant',
        ),
    ]
