# Generated by Django 2.1.7 on 2019-03-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=50)),
                ('address_1', models.CharField(max_length=50)),
                ('address_2', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=10)),
                ('county', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('notes', models.TextField()),
            ],
        ),
    ]
