# Generated by Django 2.1.7 on 2019-03-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='type',
            field=models.CharField(choices=[('SMALL_BUSINESS', 'Small Business'), ('LARGE_BUSINESS', 'Large Business'), ('SOLETRADER', 'Soletrader')], default='SMALL_BUSINESS', max_length=50),
        ),
    ]
